import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const desktopRoot = fileURLToPath(new URL('..', import.meta.url))

describe('desktop data-home chooser', () => {
  it('presents all three data strategies and the comparison dialog', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    expect(html).toContain('data-source="official"')
    expect(html).toContain('data-source="community"')
    expect(html).toContain('data-source="fresh"')
    expect(html).toContain('id="detail" class="detail" data-source="official"')
    expect(html).toContain('.choice[data-source="official"]')
    expect(html).toContain('.detail[data-source="official"]')
    expect(html).toContain('class="comparison-table-wrap"')
    expect(html).toContain('thead th[data-source="official"]')
    expect(html).toContain('thead th[data-source="community"]')
    expect(html).toContain('thead th[data-source="fresh"]')
    expect(html).toContain('@media (prefers-reduced-motion: reduce)')
    expect(html).not.toContain('reuse-column')
    expect(html).toContain('id="help"')
    expect(html).toContain('id="overlay"')
    expect(html).toContain('id="continue"')
    expect(html).toContain('id="return-main"')
    expect(html).toContain('class="footer-links"')
    expect(html).toContain('id="back" class="action secondary" type="button" data-copy="back" hidden')
    expect(html).toContain('id="destination-panel"')
    expect(html).toContain('id="portable-panel"')
    expect(html).toContain('data-migration="online"')
    expect(html).toContain('data-migration="offline"')
    expect(html).toContain('id="choose-portable"')
    expect(html).toContain('data-target="default"')
    expect(html).toContain('data-target="custom"')
    expect(html).toContain('id="choose-target"')
    expect(html).toContain('id="detail-stage" class="detail-stage" data-step="details"')
    expect(html).toContain('.detail-stage:not([data-step="details"]) .facts')
    expect(html).toContain('.detail-stage[data-step="destination"] .destination-panel')
    expect(html).toContain('.detail-stage[data-step="plugins"] .portable-panel')
    expect(html).toContain('transform: translateX(-18px)')
    expect(html).toContain('transform: translateX(18px)')
    expect(html).not.toContain('id="confirmation-overlay"')
    expect(html).toContain('默认设置')
    expect(html).toContain('自定义配置目录')
    expect(html).toContain('id="language-trigger"')
    expect(html).toContain('id="language-menu"')
    expect(html).toContain('<strong>Open DeepSeek Harness Desktop</strong>')
    expect(html).toContain('class="language-inline-label"')
    expect(html).toContain('height: 40px; width: 40px;')
    expect(html).toContain('.brand-copy strong { font-size: 18px;')
    expect(html).not.toContain('data-language="zh"')
    expect(html).not.toContain('data-language="en"')
    expect(html).not.toContain('<select id="language"')
    expect(html).toContain('id="source-panel"')
    expect(html).toContain('id="official-source"')
    expect(html).toContain('id="community-source"')
    expect(html).toContain('id="choose-official-source"')
    expect(html).toContain('id="choose-community-source"')
    expect(html).toContain('id="development-tools" class="development-tools" hidden')
    expect(html).toContain('id="simulate-missing-source"')
    expect(html).toContain('导入到独立环境')
    expect(html).toContain('id="official-source-status"')
    expect(html).toContain('id="community-source-status"')
    expect(html.indexOf('id="source-panel"')).toBeLessThan(html.indexOf('id="choices"'))
    expect(html).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(html).toContain('.source-entry + .source-entry { border-left:')
    expect(html).toContain('padding: 24px 14px')
    expect(html).not.toContain('.choice:first-child { padding-top: 8px; }')
    expect(html).toContain('color-scheme: light dark')
    expect(html).toContain('@media (prefers-color-scheme: dark)')
  })

  it('keeps the chooser sandboxed and sends only bounded selections', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    const preload = await readFile(`${desktopRoot}/src/data-home-preload.ts`, 'utf8')
    expect(html).toContain("default-src 'none'")
    expect(html).toContain("script-src 'self'")
    expect(html).toContain('<link rel="icon" href="icon.png">')
    expect(html).toContain('<script src="data-home-preview.js" defer></script>')
    expect(preload).toContain("type DataHomeMode = 'imported' | 'reused' | 'fresh'")
    expect(preload).not.toContain('document.documentElement.dataset.desktopChooser')
    expect(preload).toContain("ipcRenderer.invoke('dsh:data-home:choose-source', category)")
    expect(preload).toContain("ipcRenderer.invoke('dsh:data-home:choose-target')")
    expect(preload).toContain("ipcRenderer.invoke('dsh:data-home:choose-portable')")
    expect(preload).toContain("ipcRenderer.send('dsh:data-home:selected', selected === 'fresh'")
    expect(preload).toContain("mode: 'copied', sourceKind: origin, source, target,")
    expect(preload).toContain('{ sourceSelectionId: sources.community.selectionId }')
    expect(preload).toContain("ipcRenderer.send('dsh:data-home:cancelled')")
    expect(preload).toContain("const returnToMain = parameters.get('returnToMain') === 'true'")
    expect(preload).toContain('defaultTargetChoice.hidden = !defaultTargetAvailable')
    expect(preload).toContain("languageTrigger.addEventListener('click'")
    expect(preload).toContain("option.addEventListener('click'")
    expect(preload).toContain('const languageOptions = DESKTOP_LOCALES.map')
    expect(preload).toContain('languageMenu.replaceChildren(...languageOptions)')
    expect(preload).toContain("event.key === 'ArrowDown' || event.key === 'ArrowUp'")
    expect(preload).toContain('detailPanel.dataset.source = origin')
    expect(preload).toContain('sources[category].error = result.status')
    expect(preload).toContain("sources[category].status = 'valid'")
    expect(preload).toContain("const development = parameters.get('development') === 'true'")
    expect(preload).toContain("origin === 'official' && simulateMissingSource ? undefined : source")
    expect(preload).toContain('simulateMissingSourceButton.ariaPressed = String(simulateMissingSource)')
    expect(preload).toContain("import { copyFor, detailsFor } from './locales/data-home.ts'")
    expect(preload).toContain("type DataHomeTargetMode = 'default' | 'custom'")
    expect(preload).toContain('detailStage.dataset.step = step')
    expect(preload).toContain("backButton.hidden = step === 'details'")
    expect(preload).not.toContain('detailTitle.textContent = copy.destinationTitle')
    expect(preload).not.toMatch(/select\(mode\)\s+if \(mode !== 'reused'\) enterDestinationStep\(\)/u)
    expect(preload).toContain("if (step === 'details')")
    expect(preload).toContain('submitSelection()')
    expect(preload).not.toContain('showConfirmation')
    expect(preload).toContain("{ kind: 'custom' as const, selectionId: customTarget.selectionId }")
    expect(preload).not.toContain("target: { kind: 'custom', path:")
  })

  it('keeps long locale controls in normal header flow', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    expect(html).toContain('class="header-actions"')
    expect(html).toContain('.header-actions {')
    expect(html).toContain('flex-wrap: wrap')
    expect(html).toContain('width: max-content')
    expect(html).not.toContain('right: 204px')
  })

  it('keeps the footer inside the viewport when translated content wraps', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    const shellRule = html.match(/\.shell \{(?<rule>[^}]+)\}/u)?.groups?.rule ?? ''
    const contentRule = html.match(/\.content \{(?<rule>[^}]+)\}/u)?.groups?.rule ?? ''
    const choicesRule = html.match(/\.choices-pane \{(?<rule>[^}]+)\}/u)?.groups?.rule ?? ''
    const detailRule = html.match(/\.detail \{(?<rule>[^}]+)\}/u)?.groups?.rule ?? ''
    const footerRule = html.match(/\.footer \{(?<rule>[^}]+)\}/u)?.groups?.rule ?? ''

    expect(shellRule).toContain('height: 100vh')
    expect(shellRule).toContain('grid-template-rows: minmax(82px, auto) minmax(0, 1fr) 82px')
    expect(shellRule).toContain('overflow: hidden')
    expect(contentRule).toContain('min-height: 0')
    expect(choicesRule).toContain('overflow: auto')
    expect(detailRule).toContain('overflow-y: auto')
    expect(footerRule).toContain('min-height: 82px')
  })

  it('keeps Electron as the chooser adapter and delegates data-home decisions to the authority', async () => {
    const main = await readFile(`${desktopRoot}/src/main.ts`, 'utf8')
    expect(main).toContain("ipcMain.handle('dsh:data-home:choose-source'")
    expect(main).toContain("ipcMain.handle('dsh:data-home:choose-target'")
    expect(main).toContain('ipcMain.handle(DESKTOP_IPC.dataHomeOpenChooser')
    expect(main).toContain('session.chooseSource(origin, candidate)')
    expect(main).toContain('session.chooseTarget(')
    expect(main).toContain('session.submit(value)')
    expect(main).toContain('desktopDataHomes.initialize')
    expect(main).toContain('desktopDataHomes.change')
    expect(main).toContain('desktopDataHomes.chooseDirectory')
    expect(main).toContain('desktopDataHomes.chooseRecoveryDirectory')
    expect(main).toContain('desktopDataHomes.switch')
    expect(main).not.toContain('pendingDataHomeSelections')
    expect(main).not.toContain('resolveEmptyDesktopDataHome(pending.path)')
    expect(main).toContain("development: app.isPackaged ? 'false' : 'true'")
    expect(main).toContain("returnToMain: presentation.returnToMain ? 'true' : 'false'")
    expect(main).not.toContain('if (!await hasDesktopData(layout.officialDshHome))')
  })

  it('uses the branded icon before opening the chooser in development', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    const main = await readFile(`${desktopRoot}/src/main.ts`, 'utf8')
    const ready = main.indexOf('await app.whenReady()')
    const dockIcon = main.indexOf('applyStartupDockIcon()', ready)
    const chooser = main.indexOf('await prepareDesktopDshHome()', ready)

    expect(html).toContain('<img src="icon.png" alt="">')
    expect(ready).toBeGreaterThan(-1)
    expect(dockIcon).toBeGreaterThan(ready)
    expect(chooser).toBeGreaterThan(dockIcon)
  })
})
